from __future__ import annotations

import ast
from pathlib import Path
from typing import Iterable

from .flow import FlowError, TypeChecker, parse_file
from .flow.model import Expr, Program, Stmt

C_TYPES = {"int": "long long", "float": "double", "bool": "int", "str": "const char *", "none": "void"}


class NativeCompileError(FlowError):
    pass


class CEmitter:
    """C11 backend for the statically typed scalar subset of Synapse Flow v2.

    Bytecode remains the complete v2 execution target. This backend deliberately
    rejects dynamic containers, network builtins, and `any` rather than silently
    changing semantics.
    """

    def __init__(self, program: Program):
        self.program = program
        self.type_info = TypeChecker(program).check()
        self.indent = 0
        self.lines: list[str] = []
        self.loop_id = 0

    def emit(self) -> str:
        self.lines = [
            "/* generated by Synapse Flow v2 */",
            "#include <math.h>",
            "#include <stdio.h>",
            "#include <stdlib.h>",
            "",
            "static double syn_clamp(double v, double lo, double hi) { return v < lo ? lo : (v > hi ? hi : v); }",
            "",
        ]
        globals_env = dict(self.type_info["globals"])
        for name, type_name in globals_env.items():
            self._require_scalar(type_name, 0)
            self.lines.append(f"static {C_TYPES[type_name]} {name};")
        if globals_env:
            self.lines.append("")
        for name, st in self.program.functions.items():
            self._function(name, st, globals_env)
            self.lines.append("")
        self.lines.append("int main(void) {")
        self.indent = 1
        self._block(self.program.body, dict(globals_env), globals_scope=True)
        self._line("return 0;")
        self.indent = 0
        self.lines.append("}")
        return "\n".join(self.lines) + "\n"

    def _function(self, name: str, st: Stmt, globals_env: dict[str, str]) -> None:
        ret = st.return_type or "none"
        self._require_scalar(ret, st.line, allow_none=True)
        params = []
        env = dict(globals_env)
        for pname, ptype in st.params:
            self._require_scalar(ptype, st.line)
            params.append(f"{C_TYPES[ptype]} {pname}")
            env[pname] = ptype
        self.lines.append(f"static {C_TYPES[ret]} {name}({', '.join(params) if params else 'void'}) {{")
        self.indent = 1
        self._block(st.body, env, globals_scope=False)
        self.indent = 0
        self.lines.append("}")

    def _block(self, body: Iterable[Stmt], env: dict[str, str], *, globals_scope: bool) -> None:
        for st in body:
            if st.op in {"let", "state"}:
                assert st.name and st.type_name and st.expr
                self._require_scalar(st.type_name, st.line)
                expr = self._expr(st.expr, env)
                if globals_scope:
                    self._line(f"{st.name} = {expr};")
                else:
                    self._line(f"{C_TYPES[st.type_name]} {st.name} = {expr};")
                env[st.name] = st.type_name
            elif st.op == "set":
                assert st.name and st.expr
                self._line(f"{st.name} = {self._expr(st.expr, env)};")
            elif st.op == "emit":
                assert st.expr
                t = self._expr_type(st.expr, env)
                expr = self._expr(st.expr, env)
                if t == "str":
                    self._line(f'printf("%s\\n", {expr});')
                else:
                    self._line(f'printf("%.17g\\n", (double)({expr}));')
            elif st.op == "assert":
                assert st.expr
                self._line(f"if (!({self._expr(st.expr, env)})) {{ fprintf(stderr, \"Synapse assertion failed at line {st.line}\\n\"); return 2; }}")
            elif st.op == "expr":
                assert st.expr
                self._line(f"(void)({self._expr(st.expr, env)});")
            elif st.op == "return":
                if st.expr is None:
                    self._line("return;")
                else:
                    self._line(f"return {self._expr(st.expr, env)};")
            elif st.op == "if":
                assert st.expr
                self._line(f"if ({self._expr(st.expr, env)}) {{")
                self.indent += 1
                self._block(st.body, dict(env), globals_scope=globals_scope)
                self.indent -= 1
                if st.else_body:
                    self._line("} else {")
                    self.indent += 1
                    self._block(st.else_body, dict(env), globals_scope=globals_scope)
                    self.indent -= 1
                self._line("}")
            elif st.op == "while":
                assert st.expr
                self._line(f"while ({self._expr(st.expr, env)}) {{")
                self.indent += 1
                self._block(st.body, dict(env), globals_scope=globals_scope)
                self.indent -= 1
                self._line("}")
            elif st.op == "repeat":
                assert st.expr
                self.loop_id += 1
                loop = self.loop_id
                name = f"_syn_i_{loop}"
                self._line(f"for (long long {name}=0, _syn_n_{loop}=(long long)({self._expr(st.expr, env)}); {name}<_syn_n_{loop}; ++{name}) {{")
                self.indent += 1
                self._block(st.body, dict(env), globals_scope=globals_scope)
                self.indent -= 1
                self._line("}")
            elif st.op == "break":
                self._line("break;")
            elif st.op == "continue":
                self._line("continue;")

    def _expr_type(self, expr: Expr, env: dict[str, str]) -> str:
        checker = TypeChecker(self.program)
        return checker.expr_type(expr, env)

    def _expr(self, expr: Expr, env: dict[str, str]) -> str:
        return self._node(ast.parse(expr.source, mode="eval").body, env, expr.line)

    def _node(self, node: ast.AST, env: dict[str, str], line: int) -> str:
        if isinstance(node, ast.Constant):
            if node.value is None:
                raise NativeCompileError(f"line {line}: none is not a native scalar expression")
            if type(node.value) is bool:
                return "1" if node.value else "0"
            if type(node.value) in {int, float}:
                return repr(node.value)
            if type(node.value) is str:
                escaped = node.value.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")
                return f'"{escaped}"'
        if isinstance(node, ast.Name):
            constants = {"true":"1", "false":"0", "pi":"3.14159265358979323846", "tau":"6.28318530717958647692", "e":"2.71828182845904523536", "phi":"1.6180339887498948482"}
            if node.id.lower() in constants:
                return constants[node.id.lower()]
            if node.id in env:
                return node.id
            raise NativeCompileError(f"line {line}: unknown name {node.id}")
        if isinstance(node, ast.UnaryOp):
            op = "!" if isinstance(node.op, ast.Not) else "-" if isinstance(node.op, ast.USub) else "+"
            return f"({op}{self._node(node.operand, env, line)})"
        if isinstance(node, ast.BinOp):
            ops = {ast.Add:"+", ast.Sub:"-", ast.Mult:"*", ast.Div:"/", ast.FloorDiv:"/", ast.Mod:"%"}
            if isinstance(node.op, ast.Pow):
                return f"pow({self._node(node.left, env, line)}, {self._node(node.right, env, line)})"
            if type(node.op) not in ops:
                raise NativeCompileError(f"line {line}: native operator unsupported")
            return f"({self._node(node.left, env, line)} {ops[type(node.op)]} {self._node(node.right, env, line)})"
        if isinstance(node, ast.BoolOp):
            op = " && " if isinstance(node.op, ast.And) else " || "
            return "(" + op.join(self._node(x, env, line) for x in node.values) + ")"
        if isinstance(node, ast.Compare) and len(node.ops) == 1:
            ops = {ast.Eq:"==", ast.NotEq:"!=", ast.Lt:"<", ast.LtE:"<=", ast.Gt:">", ast.GtE:">="}
            if type(node.ops[0]) not in ops:
                raise NativeCompileError(f"line {line}: native comparison unsupported")
            return f"({self._node(node.left, env, line)} {ops[type(node.ops[0])]} {self._node(node.comparators[0], env, line)})"
        if isinstance(node, ast.IfExp):
            return f"({self._node(node.test, env, line)} ? {self._node(node.body, env, line)} : {self._node(node.orelse, env, line)})"
        if isinstance(node, ast.Call) and isinstance(node.func, ast.Name) and not node.keywords:
            name = node.func.id
            args = [self._node(x, env, line) for x in node.args]
            if name in self.program.functions:
                return f"{name}({', '.join(args)})"
            builtin = {"sqrt":"sqrt", "sin":"sin", "cos":"cos", "tanh":"tanh", "log":"log", "float":"(double)", "int":"(long long)", "clamp":"syn_clamp"}
            if name in {"float", "int"} and len(args) == 1:
                return f"{builtin[name]}({args[0]})"
            if name in builtin:
                return f"{builtin[name]}({', '.join(args)})"
            if name == "abs" and len(args) == 1:
                return f"fabs({args[0]})"
            if name in {"min", "max"} and len(args) == 2:
                cmp = "<" if name == "min" else ">"
                return f"(({args[0]}) {cmp} ({args[1]}) ? ({args[0]}) : ({args[1]}))"
            raise NativeCompileError(f"line {line}: builtin {name} is bytecode-only")
        raise NativeCompileError(f"line {line}: expression is not supported by native scalar backend")

    @staticmethod
    def _require_scalar(type_name: str, line: int, allow_none: bool = False) -> None:
        allowed = set(C_TYPES)
        if not allow_none:
            allowed.discard("none")
        if type_name not in allowed:
            raise NativeCompileError(f"line {line}: native backend supports scalar static types only; got {type_name}")

    def _line(self, text: str) -> None:
        self.lines.append("    " * self.indent + text)


def emit_c(program: Program) -> str:
    return CEmitter(program).emit()


def emit_c_file(source: str | Path, output: str | Path) -> Path:
    out = Path(output)
    out.write_text(emit_c(parse_file(source)), encoding="utf-8")
    return out
